name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

  docker-build-push:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: npm ci

      - name: Build Docker Image
        run: docker-compose up --build -d

      - name: Log in to the Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Tag and Push Docker Image to Heroku
        run: |
          docker tag docker-node:1.0 registry.heroku.com/docker-node/web
          docker push registry.heroku.com/docker-node/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release the Image to Heroku
        run: heroku container:release web -a docker-node
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
